
LIB_NAME=CoreFoundation
CFLAGS=-DDEBUG
LDLIBS=-licu -lobjc -llog
#LDFLAGS=-v -Wl,--no-undefined
OBJECTS = \
    CFArray.o \
    CFAttributedString.o \
    CFBag.o \
    CFBase.o \
    CFBinaryHeap.o \
    CFBitVector.o \
    CFCalendar.o \
    CFCharacterSet.o \
    CFData.o \
    CFDate.o \
    CFDateFormatter.o \
    CFDictionary.o \
    CFError.o \
    CFLocale.o \
    CFNumber.o \
    CFNumberFormatter.o \
    CFRunLoop.o \
    CFRuntime.o \
    CFSet.o \
    CFSocket.o \
    CFString.o \
    CFStringEncoding.o \
    CFStringFormat.o \
    CFStringUtilities.o \
    CFTimeZone.o \
    CFTree.o \
    CFURL.o \
    CFURLAccess.o \
    CFUUID.o \
    CFXMLNode.o \
    CFXMLParser.o \
    GSHashTable.o \

include ${MY_FRAMEWORKS_PATH}/resources/makefile-shared
