
#APP_NAME=HelloWorld

#OUTPUT=$(APP_NAME)
#CC=clang
#files=main.c

#all:$(files)
#	$(CC) main.c -o $(OUTPUT)


APP_NAME=HelloWorld
#CFLAGS=-DDEBUG
#LDLIBS= -lCoreFoundation -lFoundation -lCoreGraphics -lIOKit -lEGL -lGLESv1_CM -lOpenGLES -lCoreText
#LDFLAGS=-v -Wl,--no-undefined
OBJECTS = \
    main.o \

include ${MY_FRAMEWORKS_PATH}/resources/makefile-executable
