
LIB_NAME=AnimationGradients
CFLAGS=-DDEBUG -fblocks
LDLIBS= -llog -landroid -lCoreFoundation -lFoundation -lNAOpenGLES -lNACoreGraphics -lNAUIKit
OBJECTS = \
    rd_app_glue.o \
    rd_main.o \
    AppDelegate.o \
    AnimationGradientsView.o \

include ${MY_FRAMEWORKS_PATH}/resources/makefile-shared
